# Generated by Django 5.2.13 on 2026-07-25 09:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0227_alter_interface_speed_bigint'),
        ('extras', '0134_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OxidizedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('git_repo_path', models.CharField(max_length=255)),
                ('node_name_source', models.CharField(default='name', max_length=100)),
                ('api_url', models.URLField(blank=True, default='')),
                ('scope_platforms', models.ManyToManyField(blank=True, related_name='+', to='dcim.platform')),
                ('scope_roles', models.ManyToManyField(blank=True, related_name='+', to='dcim.devicerole')),
                ('scope_tags', models.ManyToManyField(blank=True, related_name='+', to='extras.tag')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Oxidized Source',
                'verbose_name_plural': 'Oxidized Sources',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConfigSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('commit_sha', models.CharField(max_length=40)),
                ('commit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('commit_subject', models.CharField(blank=True, default='', max_length=255)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.SearchVector('content', config='simple'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oxidized_snapshot', to='dcim.device')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='netbox_oxidized_viewer.oxidizedsource')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigCommitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('commit_sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxidized_commit_notes', to='dcim.device')),
            ],
            options={
                'ordering': ('created',),
                'indexes': [models.Index(fields=['device', 'commit_sha'], name='netbox_oxid_device__0031c0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='oxidizedsource',
            constraint=models.UniqueConstraint(models.Value(True), name='netbox_oxi_single_source'),
        ),
        migrations.AddIndex(
            model_name='configsnapshot',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='netbox_oxi_cfgsnapshot_sv_gin'),
        ),
    ]
