# Generated by Django 5.2.1 on 2026-09-18 08:39

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
        ('netbox_oxidized_viewer', '0002_oxidizedsource_inventory_ip_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OxidizedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('scope_platforms', models.ManyToManyField(blank=True, related_name='+', to='dcim.platform')),
                ('scope_roles', models.ManyToManyField(blank=True, related_name='+', to='dcim.devicerole')),
                ('scope_sites', models.ManyToManyField(blank=True, related_name='+', to='dcim.site')),
                ('scope_tags', models.ManyToManyField(blank=True, related_name='+', to='extras.tag')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Oxidized Inventory',
                'verbose_name_plural': 'Oxidized Inventories',
                'ordering': ('name',),
            },
        ),
    ]
