# Generated by Django 5.2.1 on 2026-09-18 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('netbox_oxidized_viewer', '0003_oxidizedinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('last_status', models.CharField(max_length=50)),
                ('last_run', models.DateTimeField()),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oxidized_backup_status', to='dcim.device')),
            ],
            options={
                'verbose_name': 'Backup status',
                'verbose_name_plural': 'Backup statuses',
            },
        ),
    ]
