# Generated by Django 5.2.13 on 2026-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_oxidized_viewer', '0005_remove_oxidizedsource_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsnapshot',
            name='commit_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='configsnapshot',
            name='commit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
